name: portfolio_v3
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.5.3'

dependencies:
  animated_text_kit: ^4.2.2
  fading_edge_scrollview: ^4.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  simple_icons: ^10.1.3
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/anims/
    - assets/img/
    - assets/json/